### ISSUE TITLE
fatal error: WiFiUDP.h: No such file or directory

### ISSUE THREAD

**Issue by rena2019** [witnessmenow/esp8266-alexa-wemo-emulator#3]
I tried to compile the examples and get:
In file included from /home/rena2019/Arduino/SingleSwitch/SingleSwitch.ino:3:0:
/home/rena2019/Arduino/libraries/esp8266-alexa-wemo-emulator-master/src/WemoSwitch.h:7:21: fatal error: WiFiUDP.h: No such file or directory
 #include <WiFiUDP.h>
                     ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
--------------------------------------------------------------------------------------------------------
my setup: Linux Mint 18.1, Arduino IDE 1.8.1 + "esp8266 by ESP8266 COMMUNITY 2.3.0" (https://github.com/esp8266/Arduino installed via http://arduino.esp8266.com/stable/package_esp8266com_index.json ), NodeMCU 1.0 (ESP-12E Module)

**Comment by witnessmenow** [comment]
Hey, I think I might have a mistake with the name of that header

In my library its WiFiUDP.h , but in esp8266 core its WiFiUdp.h (dp not upper case). 

It makes sense windows would work as it ignores cases for files, but I'm on a Mac so surprised it wasn't an issue there.

Could you try changing on the WemoSwitch.h file that's in you error and see does that work?

**Comment by rena2019** [comment]
It works after I changed "#include <WiFiUDP.h>" in both files: WemoSwitch.h + WemoManager.h to "#include <WiFiUdp.h>"

**Comment by witnessmenow** [comment]
Cool thanks for letting me know. I'll fix that when I get some time.
